Add rmm::exec_policy_nosync
rapidsai/rmm pull request #1009
Opened 2022-03-26 11:51 UTC by fkallen

Add `rmm:exec_policy_nosync`. 

For Thrust 1.16 and newer, this policy is based on `execute_on_stream_nosync_base` instead of `execute_on_stream_base` to allow Thrust algorithms to skip synchronizations.

For older Thrust versions, this is an alias to rmm::exec_policy

2022-03-26 11:51 UTC, GPUtester commented
Can one of the admins verify this patch?

2022-03-26 11:51 UTC, GPUtester commented
Can one of the admins verify this patch?

2022-03-26 21:03 UTC, rongou approved these changes

2022-03-28 16:12 UTC, jrhemstad commented
tbh, I'd been thinking about just changing the `rmm::exec_policy` to use the `nosync` version.

Technically this would be a breaking change, but I'd be surprised if anything in RAPIDS was depending on the synchronous behavior of Thrust algorithms. I suspect most would appreciate the elimination of the extra syncs.

2022-03-29 02:00 UTC, harrism commented
> but I'd be surprised if anything in RAPIDS was depending on the synchronous behavior of Thrust algorithms.

Really? I won't be surprised. Not saying I oppose it, just that we should do an investigation before flipping a switch like this.

2022-03-31 05:31 UTC, harrism commented
Just saying we should test all RAPIDS libraries before merging such a change (not just RMM tests).

2022-03-31 13:37 UTC, jrhemstad commented
> Just saying we should test all RAPIDS libraries before merging such a change (not just RMM tests). Also test Spark since they rely on PTDS.

I think I've changed my mind. I don't think the hassle of having to verify every usage of `rmm::exec_policy` is worth it. It's easy enough to find/replace `rmm::exec_policy` with `rmm::exec_policy_async` in consumer libraries.

2022-03-31 13:47 UTC, jrhemstad reviewed
Thanks @fkallen! Could you also add some tests?

2022-04-03 18:53 UTC, fkallen commented
Do you have a test in mind? I don't know how to test this other than taking a look at the profiler to check if there is a pool allocation and a missing sync.

2022-04-04 22:22 UTC, harrism approved these changes

2022-04-04 22:28 UTC, jrhemstad commented
> Do you have a test in mind? I don't know how to test this other than taking a look at the profiler to check if there is a pool allocation and a missing sync.

I was just thinking making sure that it works as a valid execution policy. So simply launch a Thrust algorithm with device data and make sure the result is sound. 

I was going to say "just do what we do for our current tests", but apparently that's nothing!

2022-04-05 00:28 UTC, harrism commented
ok to test

2022-04-05 00:29 UTC, harrism commented
rerun tests

2022-04-05 13:15 UTC, jrhemstad approved these changes

2022-04-08 21:59 UTC, cwharris requested changes
`nosync` isn't a term we use in rmm, or any rapids libraries as far as I can tell. What if we use `async`, which is common?

2022-04-08 21:59 UTC, cwharris commented on include/rmm/exec_policy.hpp
> +  explicit exec_policy_nosync(
```suggestion
  explicit exec_policy_async(
```

2022-04-08 22:00 UTC, cwharris approved these changes

2022-04-26 23:16 UTC, harrism commented
@gpucibot merge

2022-04-26 23:16 UTC, merged