Don't throw on cudaErrorInvalidValue in is_export_handle_type_supported
rapidsai/rmm pull request #1055
Opened 2022-06-01 02:12 UTC by gerashegalov

Intercept `cudaErrorInvalidValue` returned from `cudaDeviceGetAttribute`

Co-authored-by: @jrhemstad 

Closes #1054

Signed-off-by: Gera Shegalov <gera@apache.org>

2022-06-01 06:19 UTC, harrism approved these changes
Thanks for the fix!

2022-06-01 20:49 UTC, harrism requested changes
Suggesting a more complete fix.

2022-06-01 20:49 UTC, harrism commented on include/rmm/detail/dynamic_load_runtime.hpp
> +    RMM_CUDA_TRY(result);
We should change this so it always returns true for `cudaMemHandleTypeNone` even if the driver is older than CUDA 11.3. (when `cudaDevAttrMemoryPoolSupportedHandleTypes` was introduced).

```suggestion
    if (cudaMemHandleTypeNone != handle_type) {
        auto const result = cudaDeviceGetAttribute(&supported_handle_types_bitmask,
                                                   cudaDevAttrMemoryPoolSupportedHandleTypes,
                                                   rmm::detail::current_device().value());

        // Don't throw on cudaErrorInvalidValue
        auto const unsupported_runtime = (result == cudaErrorInvalidValue);
        if (unsupported_runtime) return false;
        // throw any other error that may have occurred
        RMM_CUDA_TRY(result);
    }
```

2022-06-01 23:18 UTC, harrism approved these changes

2022-06-01 23:19 UTC, harrism commented
@gerashegalov please confirm this fixes #1054 before we merge. Thanks!

2022-06-02 01:31 UTC, pxLi commented
may I ask will this be cherry-picked to 22.06?

2022-06-02 06:57 UTC, gerashegalov commented
> please confirm this fixes #1054 before we merge. Thanks!

Fix confirmed with https://github.com/rapidsai/cudf/compare/branch-22.08...gerashegalov:rmmTest?expand=1#diff-707bbf4bad4194f1803f3586af0611546f6064a20561f68e34f74f30d2ec4f55L20-R27

2022-06-03 16:40 UTC, gerashegalov commented
@gpucibot merge

2022-06-06 20:31 UTC, harrism commented
@gpucibot merge

2022-06-06 20:31 UTC, merged