Update pre-commit hooks
rapidsai/rmm pull request #1154
Opened 2022-11-09 16:17 UTC by bdice

## Description
This PR moves rmm's pre-commit hooks to be better aligned with cuDF. This will ultimately help us use pre-commit in CI style checks, but it's blocked by #1151. I will probably leave this PR as a draft, pull pieces out of it, and open some new PRs that would not be blocked by #1151. Then I can either close this PR or re-do it once #1151 is merged.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-11-09 22:57 UTC, harrism commented
Burn down starts tomorrow, so if you want to get part of this in 22.12 suggest opening the PRs now.

2022-11-10 04:48 UTC, bdice commented
@harrism It's not as time sensitive as GitHub Actions for cuDF, which is my primary project at the moment. Since this is partially blocked by #1151 anyway, I am going to de-prioritize this and come back to it at a convenient time (probably just after burndown, targeting 23.02). Since it's mostly for developer convenience, the release timing is not crucial.

2022-11-17 09:07 UTC, harrism approved these changes

2022-12-07 19:56 UTC, raydouglass approved these changes

2022-12-07 20:19 UTC, ajschmidt8 requested changes

2022-12-07 20:19 UTC, ajschmidt8 commented on ci/check_style.sh
>  set +e
```suggestion
```

now that we've removed the explicit `exit` command at the bottom of this script, this `set +e` should be removed also.

2022-12-13 02:26 UTC, harrism approved these changes

2022-12-14 01:13 UTC, ajschmidt8 approved these changes

2022-12-14 01:43 UTC, bdice commented
@gpucibot merge

2022-12-14 01:43 UTC, merged