Add groups to the doxygen docs
rapidsai/rmm pull request #1358
Opened 2023-10-11 01:04 UTC by vyasr

## Description

This PR adds doxygen groups for the various parts of the C++ API to help provide more context. This will also help with improving the docs experience in #1324.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-10-11 03:00 UTC, harrism requested changes
Thanks for doing this, @vyasr. I think a few small changes will help to group everything by function and be more aligned to what users will *do* with the library. (As apposed to having some groups about coding terminology, like "strong types").

2023-10-11 16:29 UTC, vyasr commented on include/rmm/device_buffer.hpp
> + * @addtogroup core_classes
I think I would prefer just "containers". The memory is implicit.

2023-10-11 16:40 UTC, vyasr commented on include/rmm/mr/device/owning_wrapper.hpp
> + * @addtogroup device_resource_adaptors
Yes. I had the same question, and it primarily comes from the fact that allocate and deallocate pass streams. There's also the inheritance (`owning_wrapper` inherits from `device_memory_resource`), which is a fuzzier reason but still indicative.

2023-10-11 16:45 UTC, vyasr commented on include/rmm/mr/device/owning_wrapper.hpp
> + * @return std::unique_ptr<Resource> A unique pointer to the created resource
Fair :smile: I'll fix this particular one, but we probably need a separate PR for handling this more globally.

2023-10-11 23:14 UTC, harrism commented on include/rmm/device_buffer.hpp
> + * @addtogroup core_classes
I agree memory is implicit. But `Containers` is overloaded these days (Docker containers). So maybe `Data Containers`, or `Container Classes`?

2023-10-11 23:16 UTC, harrism commented on include/rmm/mr/device/owning_wrapper.hpp
> + * @addtogroup device_resource_adaptors
OK. This will change in the future when memory kind becomes a parameter. Then we will have to rename the group.

2023-10-12 19:34 UTC, harrism approved these changes
Looks good! Thanks.

2023-10-12 23:23 UTC, vyasr commented on include/rmm/device_buffer.hpp
> + * @addtogroup core_classes
Good point. I can go with Data Containers.

2023-10-12 23:27 UTC, vyasr commented on include/rmm/mr/device/owning_wrapper.hpp
> + * @addtogroup device_resource_adaptors
For sure, and I'd be open to rearchitecturing this in a way that allows `owning_wrapper` to work for both host and device resources, but that would be a separate and larger change to make.

2023-10-12 23:28 UTC, vyasr commented
/merge

2023-10-12 23:47 UTC, merged