Replace all internal usage of `get_upstream` with `get_upstream_resource`
rapidsai/rmm pull request #1491
Opened 2024-03-01 13:49 UTC by miscco

We want to get away from raw resources, so prepare deprecation of it by replacing all internal usages

This PR relies on preparation in downstream repositories

2024-03-01 16:18 UTC, bdice approved these changes

2024-03-01 19:55 UTC, vyasr approved these changes

2024-03-01 21:43 UTC, harrism requested changes
Requesting changes to bake sure this doesn't merge before the downstream PRs are merged.

2024-03-01 21:45 UTC, harrism commented
@miscco if you would like to merge this before downstream PRs, you could move the deprecations to a separate PR that won't be merged yet.

2024-03-01 21:49 UTC, bdice commented
I'd favor splitting this PR into the new functions and then the deprecations, it does seem to help with moving the work along.

2024-03-03 10:59 UTC, miscco commented
As far as I can see, there are two occurrences of `get_upstream` outside of rmm

https://github.com/rapidsai/cudf/pull/15203
https://github.com/rapidsai/raft/pull/2207

The only one I am not 100% sure how to get rid of is one other in raft where it explicitly checks whether a resource of of a given type, which is neither possible with the current `resource_ref` not is it desired

Given that those PRs are very small and limited in scope I believe we can wait a few days getting them in

2024-03-04 03:04 UTC, harrism commented
Also the RMM Cython needs to be updated, and all uses of its current method.

2024-03-05 23:06 UTC, harrism approved these changes

2024-03-06 20:18 UTC, harrism commented
@miscco does this PR also result in changing the semantics of MR equality as discussed in #1402 ?

2024-03-08 11:42 UTC, wence- reviewed
Tiny doc nitpick.

2024-03-08 11:42 UTC, wence- commented on include/rmm/mr/device/binning_memory_resource.hpp
>     * @return rmm::mr::device_memory_resource& memory_resource that can allocate the requested size.
*nit*: `rmm::async_resource_ref`? And maybe change the `@brief` to "Get the resource reference for the requested size"?

2024-03-08 11:42 UTC, wence- commented
> Also the RMM Cython needs to be updated, and all uses of its current method.

We decided that this didn't seem to be necessary, since, for now, the Cython `get_upstream` function doesn't call into C++ (it returns a member variable of the cython class).

2024-03-14 16:13 UTC, miscco commented
/merge

2024-03-14 16:13 UTC, merged