Check if nightlies have succeeded recently enough
rapidsai/rmm pull request #1772
Opened 2024-12-20 20:53 UTC by vyasr

## Description

Contributes to https://github.com/rapidsai/build-planning/issues/127

This PR cannot be merged unless nightly CI has passed within the past 7 days, so if it remains unmerged that will itself be an indication that nightly CI needs fixing.

2024-12-20 21:11 UTC, bdice approved these changes

2024-12-20 21:12 UTC, bdice requested changes
@vyasr I'm not seeing the CI output I expected here. It doesn't show any information that indicates that it actually checked the nightly status. Is the action expected to be silent?

2024-12-20 21:24 UTC, vyasr commented
Yes, it is currently silent. If we want a positive notification we could add a corresponding print [here](https://github.com/rapidsai/shared-actions/blob/main/check_nightly_success/check-nightly-success/check.py#L64).

2024-12-21 01:50 UTC, bdice commented
Let’s add some logging, like “Checking repo X for workflow Y… workflow Y passed on 2024-12-20 12:34:56.” The silence made me unsure whether it had done any actual work.

2024-12-30 18:39 UTC, vyasr commented
> Let’s add some logging, like “Checking repo X for workflow Y… workflow Y passed on 2024-12-20 12:34:56.” The silence made me unsure whether it had done any actual work.

Done in https://github.com/rapidsai/shared-actions/pull/35, can be seen in [the rerun of the job on this PR](https://github.com/rapidsai/rmm/actions/runs/12438347535/job/34993422598?pr=1772).

2024-12-30 20:29 UTC, vyasr commented
@bdice we should be set here now.

2025-01-02 16:59 UTC, bdice commented
I have a question here that I'd like to address before approving this: https://github.com/rapidsai/shared-actions/pull/35#discussion_r1901076481

2025-01-02 20:33 UTC, bdice approved these changes

2025-01-03 04:34 UTC, vyasr commented
For the record, the request was addressed in https://github.com/rapidsai/shared-actions/pull/37.

2025-01-03 04:34 UTC, vyasr commented
/merge

2025-01-03 04:35 UTC, merged