[REVIEW] ENH Improve gpuCI scripts
rapidsai/rmm pull request #615
Opened 2020-10-22 14:51 UTC by dillon-cullinan

**Overview**
First step before "Project Flash" to improve gpuCI scripts and allow for use of different node types for CPU builds. Post "Project Flash" there will be another round of improvements and updates with the goal to make these scripts easier to maintain.

**Changes**
* Consolidates some of the CPU gpuCI scripts, reducing number of scripts to maintain
* Standardizes naming of the upload script to upload.sh
* Changes logging to use gpuci_logger where practical
* Updates comments and documentation where necessary
* Enables gpuCI to override environment variables based on node types

2020-10-22 14:52 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-23 15:18 UTC, ajschmidt8 approved these changes

2020-10-23 15:36 UTC, ajschmidt8 requested changes
looks good, just found an old `TODO` block that can be removed from the `docs/build.sh` script

2020-10-23 15:36 UTC, ajschmidt8 commented on ci/docs/build.sh
> +gpuci_conda_retry install -c anaconda beautifulsoup4 jq
similarly to the comment on Mike's PR below, this whole `TODO` block can be removed. I see `beautifulsoup4` in the [rapids-doc-env](https://github.com/rapidsai/integration/blob/branch-0.16/conda/recipes/rapids-doc-env/meta.yaml#L37-L49) and `jq` in our [gpuci devel images](https://github.com/rapidsai/gpuci-build-environment/blob/branch-0.16/rapidsai/devel.Dockerfile#L80-L83).

https://github.com/rapidsai/cudf/pull/6329#discussion_r506506128

2020-11-06 18:46 UTC, ajschmidt8 approved these changes

2020-11-06 18:47 UTC, merged