Cython extension for rmm::cuda_stream_pool
rapidsai/rmm pull request #818
Opened 2021-07-08 19:34 UTC by divyegala

2021-07-14 20:59 UTC, divyegala commented
@jakirkham could I get a review from you for the cython side? Also @jrhemstad, I have removed `explict` from the conversion operator between `rmm::cuda_stream_view` and `cudaStream_t`

2021-07-14 23:56 UTC, harrism requested changes
Just need to update the brief.

2021-07-14 23:56 UTC, harrism commented on include/rmm/cuda_stream_view.hpp
>     * @brief Explicit conversion to cudaStream_t.
```suggestion
   * @brief Implicit conversion to cudaStream_t.
```

2021-07-19 23:11 UTC, harrism approved these changes

2021-07-19 23:13 UTC, galipremsagar approved these changes

2021-07-19 23:13 UTC, shwina approved these changes

2021-07-19 23:17 UTC, harrism commented
@gpucibot merge

2021-07-19 23:17 UTC, merged