Disable opportunistic reuse in async mr when cuda driver < 11.5
rapidsai/rmm pull request #993
Opened 2022-03-14 16:09 UTC by rongou

With https://github.com/NVIDIA/spark-rapids/issues/4710 we found some issues with the async pool that may cause memory errors with older drivers. This was confirmed with the cuda team. For driver version < 11.5, we'll disable `cudaMemPoolReuseAllowOpportunistic`.

@abellina

2022-03-14 16:10 UTC, abellina approved these changes

2022-03-14 16:18 UTC, leofang requested changes
This is not fully bullet proof: the old `cudaDevAttrMemoryPoolsSupported` check needs to be kept as the support could be hardware dependent.

Also, #990 is a renovation of the async MR support, so I'd suggest to keep others in the loop.

2022-03-14 16:28 UTC, rongou commented
Added back the device attribute check.

2022-03-14 19:05 UTC, jrhemstad requested changes
There is no need to fully disable cudaMallocAsync for <11.5. We just need to disable opportunistic reuse. This is done via `cudaMemPoolSetAttribute` and setting `cudaMemPoolReuseAllowOpportunistic` to zero. 

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html#group__CUDART__MEMORY__POOLS_1g0229135f7ef724b4f479a435ca300af5

2022-03-14 19:14 UTC, rongou commented
Do we want to disable it for all cuda driver versions?

2022-03-14 19:29 UTC, jrhemstad commented
> Do we want to disable it for all cuda driver versions?

No, just for less than 11.5.

2022-03-14 21:55 UTC, rongou commented
> There is no need to fully disable cudaMallocAsync for <11.5. We just need to disable opportunistic reuse. This is done via `cudaMemPoolSetAttribute` and setting `cudaMemPoolReuseAllowOpportunistic` to zero.
> 
> https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html#group__CUDART__MEMORY__POOLS_1g0229135f7ef724b4f479a435ca300af5

Done.

2022-03-14 23:46 UTC, harrism commented
@rongou  can you please edit the title and description to better reflect the changes?

2022-03-15 00:15 UTC, jrhemstad approved these changes

2022-03-15 00:25 UTC, rongou commented
@harrism done.

2022-03-15 03:17 UTC, harrism approved these changes

2022-03-15 03:17 UTC, harrism commented
@leofang please re-review.

2022-03-16 16:43 UTC, rongou commented
@leofang please take another look. Thanks!

2022-03-16 19:10 UTC, leofang approved these changes

2022-03-16 20:01 UTC, rongou commented
@gpucibot merge

2022-03-16 20:01 UTC, merged